### ISSUE TITLE
Starter kit config [starter-kit.yaml] does not exist

### ISSUE THREAD

**Issue by litecactus** [Stillat/tidal#1]
Creating a new site through statamic and running `php please starter-kit:install Stillat/tidal` I'm getting the `Starter kit config [starter-kit.yaml] does not exist.` error. I also got this error on your "The Agency" starter kit and commented on that repo. Tried on a fresh server and same issue.

Interestingly - the first time I ran it I got this error...

```
Preparing starter kit [Stillat/tidal]...
Cleaning up temporary files...
Composer could not authenticate with GitHub!
Please generate a personal access token at: https://github.com/settings/tokens/new
Then save your token for future use by running the following command:
composer config --global --auth github-oauth.github.com [your-token-here]
Error installing starter kit [Stillat/tidal].
```

I then generated the code and ran the `composer config` command as suggested, afterwards though I thought that was weird as why would it need my GitHub? I assume the starter kit is using GitHub somehow for version control as this is a documentation focused kit but now I'm wondering if this is linked to the issue above (and the one on your other starter-kit). That might explain why we're getting the error but you aren't? Something is linked to your gh?

Food for thought but It'd be great to get this sorted. Let me know.

**Comment by JohnathonKoster** [comment]
The `Composer could not authenticate with GitHub! Please generate a personal access token at` has nothing to do with either of the starter kits, and usually means you are getting rate limited by GitHub, which can be bypassed by providing an authentication token.

I've seen this lead to partially downloaded packages before. After you've resolved your auth issue you may need to run `composer clear-cache` to clear the cache.

**Comment by litecactus** [comment]
I cleared the composer error by authenticating and still get the same error.
After clearing the cache with `composer clear-cache` I still get the same error.

**Comment by JohnathonKoster** [comment]
That's *very* interesting. I'm struggling to reproduce this issue (but do believe you are running into it).. do you happen to know which version of Composer, PHP, and the Statamic CLI tool you are running? 🤔
