### ISSUE TITLE
Search page is 404

### ISSUE THREAD

**Issue by modstore** [Stillat/tidal#2]
I've just installed this starter kit and I'm liking it, but search doesn't work. I'm new to statamic so I'm not sure if I need to enable/configure anything to make the search endpoint valid, but when I do a search, it takes me to ```/search?q=whatever``` and that is a 404 page.

**Comment by juliancarstairs** [comment]
I am getting the same issue, not really a fix, but I ran `php artisan statamic:search:update` and then replaced in `search.antlers.html` the documentation:results tag with:
```
        {{ search:results index="default" }}
              {{ if no_results }}
                  <h2>No results found for {{ get:q }}.</h2>
              {{ else }}
                  <a href="{{ url }}">
                      <h2>{{ title }}</h2>
                      <p>{{ description | truncate:180 }}</p>
                  </a>
              {{ /if }}
          {{ /search:results }}
```
Thats not really a fix though but does return results. Are there are other options I am missing in config? 
@JohnathonKoster can you assist with this?

**Comment by Julian4D** [comment]
@modstore here is the documentation for the document searcher https://stillat.com/documentation-search/v1/introduction-installation

**Comment by JohnathonKoster** [comment]
> I am getting the same issue, not really a fix, but I ran `php artisan statamic:search:update` and then replaced in `search.antlers.html` the documentation:results tag with:
> 
> ```
>         {{ search:results index="default" }}
>               {{ if no_results }}
>                   <h2>No results found for {{ get:q }}.</h2>
>               {{ else }}
>                   <a href="{{ url }}">
>                       <h2>{{ title }}</h2>
>                       <p>{{ description | truncate:180 }}</p>
>                   </a>
>               {{ /if }}
>           {{ /search:results }}
> ```
> 
> Thats not really a fix though but does return results. Are there are other options I am missing in config? @JohnathonKoster can you assist with this?

This does not sound like the same issue, as you are able to see the `search` page in order to make templating changes. The custom Tag shipped with this starter kit utilizes a custom search provider. You can learn more about configuring that here: https://stillat.com/documentation-search/v1/index-configuration

**Comment by JohnathonKoster** [comment]
@modstore  You should be able to add this to your `routes/web.php` file to resolve this (corrected for new installs, however):

```php
<?php

use Illuminate\Support\Facades\Route;

Route::statamic('search', 'search');

```

Afterwards, run `php artisan route:clear` to ensure you don't have any cached route issues 👍
